#!/usr/bin/env bash
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

base_dir=$(dirname "$0")

TASK_FILE="download_$1.tasks"

if [ ! -f "$TASK_FILE" ]; then
  echo Usage: "$0" \<task\>
  echo \<task\> is the download task to be run.
  echo Example: "$0" gn
  exit 1
fi

if [ "$1" = "win_toolchain" ]; then
  export DEPOT_TOOLS_WIN_TOOLCHAIN=2
fi

PYTHONDONTWRITEBYTECODE=1 exec python "$base_dir/gclient.py" "runtasks" "--tasksfile" "$TASK_FILE"
